In [4]:
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline

In [7]:
train= pd.read_csv('train.csv')
test=pd.read_csv('test.csv')

In [8]:
train

     PassengerId HomePlanet CryoSleep     Cabin  ...     Spa  VRDeck               Name  Transported
0        0001_01     Europa     False     B/0/P  ...     0.0     0.0    Maham Ofracculy        False
1        0002_01      Earth     False     F/0/S  ...   549.0    44.0       Juanna Vines         True
2        0003_01     Europa     False     A/0/S  ...  6715.0    49.0      Altark Susent        False
3        0003_02     Europa     False     A/0/S  ...  3329.0   193.0       Solam Susent        False
4        0004_01      Earth     False     F/1/S  ...   565.0     2.0  Willy Santantines         True
...          ...        ...       ...       ...  ...     ...     ...                ...          ...
8688     9276_01     Europa     False    A/98/P  ...  1643.0    74.0  Gravior Noxnuther        False
8689     9278_01      Earth      True  G/1499/S  ...     0.0     0.0    Kurta Mondalley        False
8690     9279_01      Earth     False  G/1500/S  ...     1.0     0.0       Fayey Connon         True
8691     9280_01     Europa     False   E/608/S  ...   353.0  3235.0   Celeon Hontichre        False
8692     9280_02     Europa     False   E/608/S  ...     0.0    12.0   Propsh Hontichre         True

[8693 rows x 14 columns]

In [9]:
test

     PassengerId HomePlanet CryoSleep     Cabin  ... ShoppingMall     Spa VRDeck              Name
0        0013_01      Earth      True     G/3/S  ...          0.0     0.0    0.0   Nelly Carsoning
1        0018_01      Earth     False     F/4/S  ...          0.0  2823.0    0.0    Lerome Peckers
2        0019_01     Europa      True     C/0/S  ...          0.0     0.0    0.0   Sabih Unhearfus
3        0021_01     Europa     False     C/1/S  ...          0.0   181.0  585.0  Meratz Caltilter
4        0023_01      Earth     False     F/5/S  ...        635.0     0.0    0.0   Brence Harperez
...          ...        ...       ...       ...  ...          ...     ...    ...               ...
4272     9266_02      Earth      True  G/1496/S  ...          0.0     0.0    0.0       Jeron Peter
4273     9269_01      Earth     False       NaN  ...         17.0    10.0  144.0     Matty Scheron
4274     9271_01       Mars      True   D/296/P  ...          0.0     0.0    0.0       Jayrin Pore
4275     9273_01     Europa     False   D/297/P  ...          0.0     0.0  523.0    Kitakan Conale
4276     9277_01      Earth      True  G/1498/S  ...          0.0     0.0    0.0  Lilace Leonzaley

[4277 rows x 13 columns]

In [10]:
X=train.drop('Transported',axis=1)
y=train['Transported']

In [11]:
cat_columns=X.select_dtypes(include=["object","bool"]).columns
num_columns=X.select_dtypes(include=["int64","float64"]).columns

In [17]:
num_transformer=SimpleImputer(strategy="median")

cat_transformer=Pipeline(
    steps=[
    ("imputer",SimpleImputer(strategy="most_frequent")),
    ("onehot",OneHotEncoder(handle_unknown="ignore"))
    ]
)

preprocess=ColumnTransformer(
    transformers=[
        ("cat",cat_transformer,cat_columns),
        ("num",num_transformer,num_columns)
    ]
)

rf=RandomForestClassifier(n_estimators=400,random_state=42)

pipeline=Pipeline([
    ("preprocess",preprocess),
    ("model",rf)
])

pipeline.fit(X,y)

prediction= pipeline.predict(test)

sub=pd.DataFrame({
    "PassengerId":test["PassengerId"],
    "Transported":prediction
})

sub.to_csv("Spaceship_submission.csv",index=False)